import { ArrowRight, CheckCircle2, Search, Sparkles, Target } from "lucide-react";
import { Link } from "react-router-dom";

const steps = [
    [Search, "01", "Analyze your website", "Enter a URL and SeoRanker inspects the page, structure, content and performance signals."],
    [Sparkles, "02", "Understand the problems", "See a clean score, prioritized issues and AI explanations for why each problem matters."],
    [Target, "03", "Track what changes", "Monitor keywords and use historical data to understand whether your work is improving visibility."],
];

export default function HowItWorks() {
    return <main className="pt-28"><section className="px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-4xl text-center"><p className="eyebrow">How it works</p><h1 className="text-5xl font-semibold tracking-[-.04em] sm:text-7xl">From a URL to a <span className="gradient-text dm-serif italic font-normal">growth plan.</span></h1><p className="section-copy mx-auto mt-6">SeoRanker turns complicated SEO data into a simple workflow you can repeat every week.</p></div><div className="mx-auto mt-16 max-w-6xl space-y-4">{steps.map(([Icon,num,title,text])=><div key={num as string} className="grid gap-6 rounded-3xl border border-border bg-card p-7 md:grid-cols-[110px_70px_1fr] md:items-center"><span className="text-5xl font-semibold text-accent/20">{num as string}</span><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-accent/10 text-accent"><Icon size={21}/></div><div><h2 className="text-xl font-semibold">{title as string}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{text as string}</p></div></div>)}</div></section><section className="bg-muted/30 px-4 py-24 sm:px-6"><div className="mx-auto max-w-5xl text-center"><h2 className="text-3xl font-semibold sm:text-5xl">A better SEO habit starts with visibility.</h2><div className="mx-auto mt-8 grid max-w-3xl gap-3 text-left sm:grid-cols-3">{['Know what is wrong','Know what matters','Know what improved'].map(x=><div key={x} className="rounded-2xl border border-border bg-card p-5"><CheckCircle2 className="text-emerald-500" size={19}/><p className="mt-4 text-sm font-semibold">{x}</p></div>)}</div><Link to="/register" className="mt-9 inline-flex items-center gap-2 rounded-xl bg-foreground px-5 py-3 text-sm font-semibold text-background">Start analyzing <ArrowRight size={15}/></Link></div></section></main>;
}
